# Generated by Django 5.2.4 on 2025-07-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0003_alter_anagrafica_codice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendentedettaglio',
            name='giorni_lavorativi_settimana',
            field=models.IntegerField(default=5, verbose_name='Giorni Lavorativi a Settimana'),
        ),
        migrations.AddField(
            model_name='dipendentedettaglio',
            name='ore_settimanali_contratto',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=4, verbose_name='Ore Settimanali da Contratto'),
        ),
    ]
