# Generated by Django 5.2.4 on 2025-08-02 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0008_cantiere_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anagrafiche', to='tenants.company'),
            preserve_default=False,
        ),
    ]
