# Generated by Django 5.2.4 on 2025-08-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0016_diarioattivita_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquotaiva',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='causale',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dipendentedettaglio',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentoriga',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mezzoaziendale',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modalitapagamento',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scadenzapersonale',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiposcadenzapersonale',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
            preserve_default=False,
        ),
    ]
