# Generated by Django 5.2.4 on 2025-07-25 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Nome Azienda')),
                ('vat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Partita IVA')),
                ('db_name', models.CharField(max_length=255, unique=True, verbose_name='Nome Database Tenant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
            ],
            options={
                'verbose_name': 'Azienda',
                'verbose_name_plural': 'Aziende',
            },
        ),
        migrations.CreateModel(
            name='UserCompanyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_role', models.CharField(choices=[('admin', 'Amministratore'), ('contabile', 'Contabile'), ('visualizzatore', 'Visualizzatore')], max_length=20, verbose_name='Ruolo Aziendale')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.company', verbose_name='Azienda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Permesso Utente-Azienda',
                'verbose_name_plural': 'Permessi Utente-Azienda',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
