# Generated by Django 5.2.4 on 2025-08-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='db_name',
        ),
    ]
