# Generated by Django 5.2.4 on 2025-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_company_address_company_email_company_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cap',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Città'),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia'),
        ),
    ]
