# Generated by Django 5.2.4 on 2025-07-25 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotaIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, verbose_name='Descrizione')),
                ('valore_percentuale', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valore %')),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aliquota IVA',
                'verbose_name_plural': 'Aliquote IVA',
                'ordering': ['valore_percentuale'],
            },
        ),
        migrations.CreateModel(
            name='ModalitaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, unique=True, verbose_name='Descrizione')),
                ('giorni_scadenza', models.IntegerField(default=30, verbose_name='Giorni a scadere di default')),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modalità di Pagamento',
                'verbose_name_plural': 'Modalità di Pagamento',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True, verbose_name='Codice Anagrafica')),
                ('tipo', models.CharField(choices=[('Cliente', 'Cliente'), ('Fornitore', 'Fornitore'), ('Dipendente', 'Dipendente')], max_length=20, verbose_name='Tipo Anagrafica')),
                ('nome_cognome_ragione_sociale', models.CharField(max_length=255, verbose_name='Nome/Cognome o Ragione Sociale')),
                ('p_iva', models.CharField(blank=True, max_length=16, null=True, verbose_name='Partita IVA')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice Fiscale')),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('cap', models.CharField(blank=True, max_length=10, null=True, verbose_name='CAP')),
                ('citta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Città')),
                ('provincia', models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anagrafiche_create', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anagrafiche_aggiornate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anagrafica',
                'verbose_name_plural': 'Anagrafiche',
                'ordering': ['nome_cognome_ragione_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_cantiere', models.CharField(max_length=50, unique=True, verbose_name='Codice Cantiere')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inizio', models.DateField(blank=True, null=True, verbose_name='Data Inizio Lavori')),
                ('data_fine_prevista', models.DateField(blank=True, null=True, verbose_name='Data Fine Prevista')),
                ('stato', models.CharField(choices=[('Bozza', 'Bozza'), ('Aperto', 'Aperto'), ('Sospeso', 'Sospeso'), ('Chiuso', 'Chiuso')], default='Bozza', max_length=20)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'Cliente'}, on_delete=django.db.models.deletion.PROTECT, to='gestionale.anagrafica', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cantieri_creati', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cantieri_aggiornati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cantiere',
                'verbose_name_plural': 'Cantieri',
                'ordering': ['-data_inizio', 'codice_cantiere'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTestata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('FTV', 'Fattura di Vendita'), ('NCV', 'Nota di Credito di Vendita')], max_length=10, verbose_name='Tipo Documento')),
                ('data_documento', models.DateField(verbose_name='Data Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Numero Documento')),
                ('imponibile', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IVA')),
                ('totale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('Bozza', 'Bozza'), ('Confermato', 'Confermato'), ('Annullato', 'Annullato')], default='Bozza', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anagrafica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documenti', to='gestionale.anagrafica', verbose_name='Cliente/Fornitore')),
                ('cantiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionale.cantiere', verbose_name='Cantiere Associato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_creati', to=settings.AUTH_USER_MODEL)),
                ('fattura_collegata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionale.documentotestata', verbose_name='Fattura Collegata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_aggiornati', to=settings.AUTH_USER_MODEL)),
                ('modalita_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionale.modalitapagamento', verbose_name='Modalità di Pagamento')),
            ],
            options={
                'verbose_name': 'Documento (Testata)',
                'verbose_name_plural': 'Documenti (Testate)',
                'ordering': ['-data_documento', '-numero_documento'],
                'unique_together': {('anagrafica', 'tipo_doc', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoRiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('quantita', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantità')),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imponibile_riga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_riga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA Riga')),
                ('aliquota_iva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionale.aliquotaiva', verbose_name='Aliquota IVA')),
                ('testata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='gestionale.documentotestata', verbose_name='Testata Documento')),
            ],
            options={
                'verbose_name': 'Riga Documento',
                'verbose_name_plural': 'Righe Documenti',
            },
        ),
    ]
