# Generated by Django 5.2.4 on 2025-07-25 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Causale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255, unique=True)),
                ('tipo_movimento', models.CharField(blank=True, help_text='Es: Pagamento Fattura, Incasso, Costo', max_length=50, null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Causale',
                'verbose_name_plural': 'Causali',
            },
        ),
        migrations.CreateModel(
            name='ContoFinanziario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conto', models.CharField(max_length=100, unique=True, verbose_name='Nome Conto')),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conto Finanziario',
                'verbose_name_plural': 'Conti Finanziari',
            },
        ),
        migrations.CreateModel(
            name='ContoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conto', models.CharField(max_length=100, unique=True, verbose_name='Nome Conto')),
                ('tipo', models.CharField(choices=[('Costo', 'Costo'), ('Ricavo', 'Ricavo')], max_length=10, verbose_name='Tipo')),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conto Operativo',
                'verbose_name_plural': 'Conti Operativi',
            },
        ),
        migrations.CreateModel(
            name='DipendenteDettaglio',
            fields=[
                ('anagrafica', models.OneToOneField(limit_choices_to={'tipo': 'Dipendente'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dettaglio_dipendente', serialize=False, to='gestionale.anagrafica')),
                ('mansione', models.CharField(max_length=100)),
                ('data_assunzione', models.DateField()),
                ('data_fine_rapporto', models.DateField(blank=True, null=True)),
                ('costo_orario', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('note_generali', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dettaglio Dipendente',
                'verbose_name_plural': 'Dettagli Dipendenti',
            },
        ),
        migrations.CreateModel(
            name='MezzoAziendale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=20, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, help_text='Es: Furgone, Autovettura, Escavatore', max_length=50, null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mezzo Aziendale',
                'verbose_name_plural': 'Mezzi Aziendali',
            },
        ),
        migrations.CreateModel(
            name='TipoScadenzaPersonale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, unique=True)),
                ('validita_mesi', models.IntegerField(blank=True, help_text='Numero di mesi di validità. Lasciare vuoto se non applicabile.', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Scadenza Personale',
                'verbose_name_plural': 'Tipi Scadenze Personale',
            },
        ),
        migrations.CreateModel(
            name='Scadenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scadenza', models.DateField(verbose_name='Data di Scadenza')),
                ('importo_rata', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo Rata')),
                ('stato', models.CharField(choices=[('Aperta', 'Aperta'), ('Parziale', 'Pagata Parzialmente'), ('Saldata', 'Saldata'), ('Annullata', 'Annullata')], default='Aperta', max_length=20)),
                ('tipo_scadenza', models.CharField(choices=[('Incasso', 'Incasso da Cliente'), ('Pagamento', 'Pagamento a Fornitore')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anagrafica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scadenze', to='gestionale.anagrafica')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='gestionale.documentotestata')),
            ],
            options={
                'verbose_name': 'Scadenza',
                'verbose_name_plural': 'Scadenze',
                'ordering': ['data_scadenza'],
            },
        ),
        migrations.CreateModel(
            name='PrimaNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField()),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione Movimento')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_movimento', models.CharField(choices=[('E', 'Entrata'), ('U', 'Uscita')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anagrafica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_primanota', to='gestionale.anagrafica')),
                ('cantiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_primanota', to='gestionale.cantiere')),
                ('causale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='gestionale.causale', verbose_name='Causale')),
                ('conto_finanziario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='gestionale.contofinanziario', verbose_name='Conto Finanziario')),
                ('conto_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='gestionale.contooperativo', verbose_name='Conto Operativo (Costo/Ricavo)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primanota_create', to=settings.AUTH_USER_MODEL)),
                ('scadenza_collegata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamenti', to='gestionale.scadenza')),
            ],
            options={
                'verbose_name': 'Prima Nota',
                'verbose_name_plural': 'Prima Nota',
                'ordering': ['-data_registrazione'],
            },
        ),
        migrations.CreateModel(
            name='ScadenzaPersonale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_esecuzione', models.DateField()),
                ('data_scadenza', models.DateField()),
                ('stato', models.CharField(choices=[('Valida', 'Valida'), ('Scaduta', 'Scaduta'), ('Rinnovata', 'Rinnovata')], default='Valida', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dipendente', models.ForeignKey(limit_choices_to={'tipo': 'Dipendente'}, on_delete=django.db.models.deletion.CASCADE, related_name='scadenze_personali', to='gestionale.anagrafica')),
                ('tipo_scadenza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionale.tiposcadenzapersonale')),
            ],
            options={
                'verbose_name': 'Scadenza Personale',
                'verbose_name_plural': 'Scadenze Personale',
                'ordering': ['data_scadenza'],
            },
        ),
        migrations.CreateModel(
            name='DiarioAttivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('stato_presenza', models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Assente Giustificato', 'Assente Giustificato'), ('Assente Ingiustificato', 'Assente Ingiustificato')], max_length=30, null=True)),
                ('tipo_assenza_giustificata', models.CharField(blank=True, help_text='Es: Ferie, Malattia, Permesso', max_length=100, null=True)),
                ('ore_ordinarie', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('ore_straordinarie', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('costo_orario_consuntivo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo orario del giorno, se diverso dallo standard', max_digits=6, null=True)),
                ('note_giornaliere', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantiere_pianificato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personale_pianificato', to='gestionale.cantiere')),
                ('dipendente', models.ForeignKey(limit_choices_to={'tipo': 'Dipendente'}, on_delete=django.db.models.deletion.PROTECT, related_name='diario', to='gestionale.anagrafica')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mezzo_pianificato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilizzi_pianificati', to='gestionale.mezzoaziendale')),
            ],
            options={
                'verbose_name': 'Diario Attività',
                'verbose_name_plural': 'Diari Attività',
                'ordering': ['-data', 'dipendente'],
                'unique_together': {('data', 'dipendente')},
            },
        ),
    ]
