# Generated by Django 5.2.4 on 2025-08-03 09:48

from django.db import migrations, models
from tenants.models import Company 
import django.db.models.deletion 
from django.db.models import ForeignKey


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoriga',
            name='tenant',
            field=ForeignKey(
                default=1,  # Sostituisci con l'ID del tuo tenant predefinito
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gestionale_documentoriga_related',
                to='tenants.company',
            ),
            preserve_default=False,  # Imposta a False per non mantenere il default dopo la migrazione
        ),
    ]
