# Generated by Django 5.2.4 on 2025-07-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0002_causale_contofinanziario_contooperativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='codice',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Codice Anagrafica'),
        ),
    ]
