# Generated by Django 5.2.4 on 2025-08-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0003_add_tenant_id_to_dipendentedettaglio'),
        ('tenants', '0004_company_cap_company_city_company_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causale',
            name='tipo_movimento',
        ),
        migrations.AddField(
            model_name='causale',
            name='tipo_movimento_default',
            field=models.CharField(blank=True, choices=[('E', 'Entrata'), ('U', 'Uscita'), ('M', 'Misto/Giroconto')], help_text='Se impostato, pre-compilerà il tipo di movimento nella Prima Nota.', max_length=1, null=True, verbose_name='Tipo Movimento di Default'),
        ),
        migrations.AlterField(
            model_name='dipendentedettaglio',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
        ),
        migrations.AlterField(
            model_name='documentoriga',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.company'),
        ),
    ]
