# Generated by Django 5.2.4 on 2025-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0004_dipendentedettaglio_giorni_lavorativi_settimana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendentedettaglio',
            name='costo_orario',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
