# Generated by Django 5.2.4 on 2025-07-27 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0005_alter_dipendentedettaglio_costo_orario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primanota',
            options={'ordering': ['data_registrazione', 'pk'], 'verbose_name': 'Prima Nota', 'verbose_name_plural': 'Prima Nota'},
        ),
        migrations.AddField(
            model_name='primanota',
            name='movimento_collegato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimento_speculare', to='gestionale.primanota'),
        ),
        migrations.AlterField(
            model_name='documentotestata',
            name='tipo_doc',
            field=models.CharField(choices=[('FTV', 'Fattura di Vendita'), ('NCV', 'Nota di Credito di Vendita'), ('FTA', 'Fattura di Acquisto'), ('NCA', 'Nota di Credito di Acquisto')], max_length=10, verbose_name='Tipo Documento'),
        ),
    ]
