# Generated by Django 5.2.4 on 2025-08-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0010_documentotestata_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primanota',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primanota', to='tenants.company'),
            preserve_default=False,
        ),
    ]
